import React from 'react';
import { AppMode } from '../types';

interface HomePageProps {
  onNavigate: (mode: AppMode) => void;
}

const HomePage: React.FC<HomePageProps> = ({ onNavigate }) => {
  return (
    <div className="flex flex-col items-center text-center space-y-12">
      <div className="space-y-4 max-w-2xl animate-fade-in-up">
        <h1 className="text-5xl font-extrabold text-transparent bg-clip-text bg-gradient-to-r from-teal-400 to-cyan-500">
          Discover the World <br /> Story by Story
        </h1>
        <p className="text-xl text-gray-400">
          Create immersive geo-tours with AI-powered descriptions and audio guides. 
          Follow paths, learn history, and explore like a local.
        </p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-8 w-full max-w-4xl">
        <div 
          onClick={() => onNavigate(AppMode.CONSUMER)}
          className="group cursor-pointer bg-gray-800 p-8 rounded-2xl border border-gray-700 hover:border-primary transition duration-300 transform hover:-translate-y-1 shadow-xl"
        >
          <div className="h-16 w-16 bg-teal-900 rounded-full flex items-center justify-center mb-6 mx-auto group-hover:bg-primary transition-colors">
            <i className="fa-solid fa-compass text-2xl text-teal-200"></i>
          </div>
          <h2 className="text-2xl font-bold mb-2">For Explorers</h2>
          <p className="text-gray-400">Find tours near you, listen to audio guides generated by Gemini, and track your path on the map.</p>
        </div>

        <div 
           onClick={() => onNavigate(AppMode.CREATOR)}
           className="group cursor-pointer bg-gray-800 p-8 rounded-2xl border border-gray-700 hover:border-accent transition duration-300 transform hover:-translate-y-1 shadow-xl"
        >
          <div className="h-16 w-16 bg-amber-900 rounded-full flex items-center justify-center mb-6 mx-auto group-hover:bg-accent transition-colors">
            <i className="fa-solid fa-pen-nib text-2xl text-amber-200"></i>
          </div>
          <h2 className="text-2xl font-bold mb-2">For Creators</h2>
          <p className="text-gray-400">Build tours effortlessly. Use AI to auto-fill descriptions and coordinates for your favorite spots.</p>
        </div>
      </div>
      
      <div className="mt-12 p-6 bg-gray-900 rounded-lg border border-gray-800 max-w-lg">
        <h3 className="text-lg font-semibold text-gray-300 mb-2">Tech Stack Demo</h3>
        <p className="text-sm text-gray-500">
           This app demonstrates a dual-storage layer. It defaults to LocalStorage but includes a full 
           <code className="text-accent bg-gray-800 px-1 rounded">storageService</code> adapter that can toggle to a Node.js Backend API.
        </p>
      </div>
    </div>
  );
};

export default HomePage;